name: practice
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/seed1.png
    - assets/images/seed2.png
    - assets/images/seed3.png
    - assets/images/seed4.png
    - assets/images/seed5.png

  fonts:
    - family: Playfair
      fonts:
        - asset: lib/fonts/PlayfairDisplay-Black.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

